language: objective-c
osx_image: xcode8
script:
- set -o pipefail
- xcodebuild -project JSONSchema.xcodeproj -scheme JSONSchema test -sdk macosx| xcpretty -c
- xcodebuild -project JSONSchema.xcodeproj -scheme JSONSchema test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
